name: DevOps
on: [push]

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
    deploy:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
